version: '3'

networks:
  zs:
    driver: ${NETWORKS_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

services:
    web:
      image: anineto/zendserver
      environment:
        - ZS_ADMIN_PASSWORD=${ZS_ADMIN_PASSWORD}
        - ZEND_LICENSE_ORDER=${ZEND_LICENSE_ORDER}
        - ZEND_LICENSE_KEY=${ZEND_LICENSE_KEY}
      volumes:
        - ${APP_CODE_PATH_HOST}:/var/www
        - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      ports:
        - "${HTTP_PORT}:80"
        - "${ZS_PORT}:10081"
      networks:
        zs:
          ipv4_address: ${DOCKER_HOST_IP}